### PR TITLE
Add Chinese translation to homepage

### PR DESCRIPTION
**Pull request by neighbor-bear**

### CODE REVIEW

**Comment by ElectronicHimate** [comment]
7.1fix2and6.1fix14-A5 ?

**Comment by ElectronicHimate** [comment]
@afeimod 7.1fix2and6.1fix14-A5 ?

**Comment by alexis850elmejor** [comment]
@afeimod Broadcasting doesn't work, the app can't be downloaded, fix that.

**Comment by alexis850elmejor** [comment]
@afeimod Broadcasting doesn't work, the app can't be downloaded, fix that.

**Comment by Oneline8** [comment]
@afeimod **[Winlator10.1-Amod3fix2.apk](https://github.com/afeimod/winlator-mod/releases/download/10.1hotfix-Amod3fix2/Winlator10.1-Amod3fix2.apk) contains malware!**

assets/rootfs_patches.tzst->(ZStandard)->./home/xuser/.wine/drive_c/windows/DOSBox/dosbox_debug.exe
https://www.virustotal.com/gui/file/5ce5f9658bd3a833e2b635b01f8318ee172ffefc4a00085a1e34fefb819df14b

assets/rootfs_patches.tzst->(ZStandard)->./home/xuser/.wine/drive_c/windows/DOSBox/dosbox.exe
https://www.virustotal.com/gui/file/d797a3867fe3b8b97a6f3319a210285dd468c4f89ee2aa1b457432f7923185be

assets/rootfs_patches.tzst->(ZStandard)->./opt/apps/d7d8tod9/cncddraw7.1.7z->syswow64/ddraw.dll
https://www.virustotal.com/gui/file/c0874fd2bbb6741d8f5e8d111a2857fefc3b9079bffd66ce17dd0306a0c44f24

assets/rootfs_patches.tzst->(ZStandard)->./opt/apps/d7d8tod9/dxwrapper1.275.7z->syswow64/ddraw.dll
https://www.virustotal.com/gui/file/7b3fc36c5b27dd8d3af2c456f64f9983072a1631c53e0c849feae6ef6f4e832f

assets/rootfs_patches.tzst->(ZStandard)->./usr/bin/ib.exe
https://www.virustotal.com/gui/file-analysis/ZWFmMWUwZDA0MGViNzdjYjYxMmQxNjBiYjBhNjZhYTE6MTc2NzM4MDUwMQ==

assets/dxwrapper/cnc-ddraw-6.6/ddraw.tzst->(ZStandard)->./syswow64/ddraw.dll
https://www.virustotal.com/gui/file/c0874fd2bbb6741d8f5e8d111a2857fefc3b9079bffd66ce17dd0306a0c44f24

**Pull request merged**
